services:
  agent-pptx:
    build: .
    container_name: agent-pptx
    environment:
      - MONGO_URL=mongodb://agents-mongo:27017
      - DB_NAME=agent-pptx
    stdin_open: true
    ports:
      - "5000"
    tty: true
    networks:
      - agents-net
      - agents-db-net


networks:
  agents-net:
    external: true
  agents-db-net:
    external: true
